use_frameworks!

platform :ios, '8.0'

target 'FFCategory_Example' do
  pod 'FFCategory', :path => '../'

  target 'FFCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
